# from
FROM python:3.12-slim
LABEL maintainer="Jamie Seol <theeluwin@gmail.com>"

# prepare
RUN mkdir --parents /src
RUN mkdir --parents /dist
WORKDIR /src

# install packages
COPY requirements.txt .
RUN pip install --requirement requirements.txt

# run
EXPOSE 8000
CMD ["./entrypoint.dev.sh"]
